# Generated by Django 4.2.1 on 2023-06-05 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joined_date',
            field=models.DateField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.IntegerField(default=datetime.date),
            preserve_default=False,
        ),
    ]
